In [1]:
%load_ext autoreload
%autoreload 2

import sys
import os
HERE = %pwd
sys.path.append(os.path.dirname(HERE))

%matplotlib inline
import matplotlib.pyplot as plt
from IPython.display import display
    
import numpy as np
import pandas as pd
import copy
import pickle
import time
import collections
from tqdm import tqdm

In [2]:
from src import utils
rng = utils.set_seed()

dir_parent = utils.dir_parent
version_exp = utils.version_exp
dir_workspace = f"{dir_parent}/research/TFCSR"

In [3]:
dir_load = f"{dir_parent}/received_data/amazon23"

# parameters
n_positive = 2
n_candidate = 50 - n_positive
n_user = 500

In [4]:
import gzip
import json
from tqdm import tqdm


def _records(path_records):
    g = gzip.open(path_records, 'rb')
    dict_ = {}
    idx = 0
    for l in tqdm(g):
        d_ = json.loads(l)
    
        try:
            user = d_['user_id']
            item = d_['parent_asin']
            rating = d_['rating']
            
            time = d_["timestamp"]
            #text = utils.to_text(d_["text"])
    
            if d_['verified_purchase'] is True:
                l = [item, rating, time]
                if user in dict_.keys():
                    dict_[user].append(l)
                else:
                    dict_[user] = [l]
        except:
            pass
    
    # transform dict to pandas.DataFrame
    def _reshape(user):
        df = pd.DataFrame(dict_[user], columns=['itemID', 'rating', 'time'])
        df.insert(0, "userID", user)
        return df
    
    df_ = pd.concat([_reshape(user) for user in tqdm(dict_.keys())])
    df_.reset_index(inplace=True, drop=True)
    
    # sort chronological order
    df_ = df_.sort_values(by="time", ascending=False)  
    
    df_["userID"] = [f"U_{i}" for i in df_["userID"].values]
    df_["itemID"] = [f"I_{i}" for i in df_["itemID"].values]
    
    # delete dupicated items
    df_records = df_.drop_duplicates(subset=["userID", "itemID"], keep='first').reset_index(drop=True)
    return df_records


def _items(path_items):
    g = gzip.open(path_items, 'rb')
    dict_ = {}
    idx = 0
    for l in tqdm(g):
        d_ = json.loads(l)
        item = d_["parent_asin"]
        
        # title
        try:
            title = utils.to_text(d_['title'])
        except:
            title = ""
    
        ## long word title tends to be weird, so skip it
        ## short word title tends to be weird, so skip it
        if (utils.compute_token(title) > 200) or (len(set(title)) <= 3):
            title = ""
        
        # category
        try:
            cat = d_['categories']
            cat = [utils.to_text(c.replace("&amp;", "&")) for c in cat[1:]]
            cat = [c for c in cat if len(c) <= 50]
            categories = ", ".join(cat)
        except:
            categories = ""
        
        # description
        try:
            description = utils.to_text(", ".join(d_['description']))
    
            ## remove short description
            if len(set(description)) <= 10:
                description = ""
    
            ## delete items whose description were longer than 300 tokens
            if utils.compute_token(description) >= 300:
                description = ""
        except:
            description = ""
    
        l = [title, categories, description]
        if item in dict_.keys():
            # update longer description
            if len(description) > len(dict_[item][2]):
                dict_[item] = l
        else:
            dict_[item] = l
    
    df_ = pd.DataFrame(dict_, index=["title", "category", "description"]).T
    df_ = df_.dropna()
    df_.index = [f"I_{i}" for i in df_.index]
    
    df_items = df_[df_["title"] != ""]   
    return df_items

def _remove_un_used_items(df_records, df_items):
    # items registered in item master
    items_master = set(df_items.index.values)

    # items that are not super long tail
    s = df_records["itemID"].value_counts()
    items_freq = set(s[s>1].index.values)
    items_master = items_master.intersection(items_freq)
    
    # restrict transaction records whose rows are registered in items_master.
    s = df_records['itemID'].apply(lambda s : s in items_master)
    df_r = df_records[s]

    # restrict item master to items registered in restricted transaction records
    df_i = df_items.loc[df_r['itemID'].unique()]
    return df_r, df_i

In [5]:
data_names = [
    "CDs_and_Vinyl", "Movies_and_TV", "Toys_and_Games", "Sports_and_Outdoors"
]
N_icl = [1, 3, 5, 10]

for data_name in data_names:
    print(data_name)
    dir_data = f"{dir_workspace}/preprocessed_data/{version_exp}/ARD_{data_name}"
    os.makedirs(dir_data, exist_ok=True)

    # create preprocessed data
    try:
        for n_icl in N_icl:
            user_type = f"{n_icl}-sample"
            with open(f"{dir_data}/records_{user_type}.pickle", 'rb') as f:
                d_data = pickle.load(f)
            user = list(d_data.keys())[-1]
            print(user_type, d_data[user])
        
        for item_type in ["history", "candidates"]:
            df_i = pd.read_csv(f"{dir_data}/items_{item_type}.csv", index_col=0)
            display(df_i.head())        
            print(item_type, len(df_i))
    except:
        # load full preprocessed data
        try:
            with open(f"{dir_data}/records.pickle", 'rb') as f:
                df_records = pd.DataFrame(pickle.load(f)).T.infer_objects(copy=False)
            with open(f"{dir_data}/items.pickle", 'rb') as f:
                df_items = pd.DataFrame(pickle.load(f)).T.infer_objects(copy=False)
        except:
            path_records = f"{dir_load}/{data_name}.jsonl.gz"
            df_records = _records(path_records)
            
            path_items = f"{dir_load}/meta_{data_name}.jsonl.gz"
            df_items = _items(path_items)
        
            df_records, df_items = _remove_un_used_items(df_records, df_items)

            with open(f"{dir_data}/records.pickle", 'wb') as f:
                pickle.dump(df_records.T.to_dict(), f)
            with open(f"{dir_data}/items.pickle", 'wb') as f:
                pickle.dump(df_items.T.to_dict(), f)                

        # remove NaN description
        df_items = df_items[df_items["description"] != ""]
        df_records, df_items = _remove_un_used_items(df_records, df_items)
        
        # ================ prepare ================ 
        # frequent items up to rank 10000
        s = df_records["itemID"].value_counts()
        s = s.sort_values(ascending=False).iloc[:1000]
        set_items = set(s.index)
        
        gb = df_records.groupby("userID")
        users = df_records["userID"].unique()
        k = -1*n_positive
        
        def _items_user(user, gb):
            df_ = gb.get_group(user).sort_values(by="time", ascending=True)
            df_ = df_[df_["rating"] > 3]
            items_user = df_["itemID"].values    
            return items_user
        
        def _candidate_items(items_user, set_items, k, n_candidate):
            items_pos = items_user[k:]  # latest k items
            items_neg = rng.choice(list(set_items - set(items_user)), size=n_candidate, replace=False)      
            d_ = {
                "candidates_positive" : ", ".join(items_pos),
                "candidates_negative" : ", ".join(items_neg)
            }
            return copy.deepcopy(d_)
        
        # ================ User history ================ 
        dd_data = dict()
        for n_icl in N_icl:
            # shuffle
            users = rng.choice(users, size=len(users), replace=False)
            
            d_data = dict()
            idx = 0
            for user in tqdm(users, desc=f"{n_icl:2}-sample"):
                items_user = _items_user(user, gb)
                
                if len(items_user) >= n_icl + n_positive:
                    try:
                        # candidate items
                        d_ = _candidate_items(items_user, set_items, k, n_candidate)
                        
                        # user history (except latest k items)
                        d_["history"] = {i+1 : item for i,item in enumerate(items_user[:k][::-1][:n_icl])} 
                        d_data[user] = copy.deepcopy(d_)
                        idx += 1
                    except:
                        pass
                
                if idx == n_user:
                    print(user, d_data[user])
                    break

            dd_data[f"{n_icl}-sample"] = copy.deepcopy(d_data)
    
        # ================ Save ================ 
        d_item = dict()
        for user_type, d_data in dd_data.items():
            with open(f"{dir_data}/records_{user_type}.pickle", 'wb') as f:
                pickle.dump(d_data, f)
            
            # items that used in the main experiments
            try:
                items_history = np.unique(np.concatenate([list(d["history"].values()) for d in d_data.values()]))
            except:
                items_history = []
            
            items_pos = np.unique(np.concatenate([d["candidates_positive"].split(", ") for d in d_data.values()]))
            items_neg = np.unique(np.concatenate([d["candidates_negative"].split(", ") for d in d_data.values()]))
            items_candidates = np.unique(np.concatenate([items_pos, items_neg]))
                    
            d_item[user_type] = {
                "history" : items_history,
                "candidates" : items_candidates
            }
            
        for item_type in ["history", "candidates"]:
            items_ = np.unique(np.concatenate([d[item_type] for d in d_item.values()]))
            df_i = df_items.loc[items_]
            df_i.to_csv(f"{dir_data}/items_{item_type}.csv")

CDs_and_Vinyl
1-sample {'candidates_positive': 'I_B000002LSV, I_B000001EYI', 'candidates_negative': 'I_B00BY8DIT2, I_B00914JWSW, I_B0168KQSYM, I_B078SKX6ZV, I_B008O9V4C2, I_B079PDLQV5, I_B004ZN9T00, I_B074YCSNT4, I_B004KBSQBA, I_B000E6EJAW, I_B01NH3ABQH, I_B008FSCNTK, I_B006ZCWU5K, I_B012DXW5DQ, I_B01GGJV5VQ, I_B00006L736, I_B006ZZAMWK, I_B00T3YBPLC, I_B000002GCB, I_B0039TD7PY, I_B019CL2SF2, I_B01L2ZS87S, I_B00LTM1D5O, I_B00000K3WY, I_B005MQNDVK, I_B000002JUC, I_B003V6L94Q, I_B00C81AVNU, I_B001U9BRNE, I_B00005NKKN, I_B079FLRBVM, I_B000089RV6, I_B001AQTWF2, I_B00OMKEK64, I_B00N0T38LG, I_B000WAEJZ0, I_B0007OY474, I_B00631VJIC, I_B00942S4OY, I_B00A1EOBJQ, I_B08HGB71RT, I_B0002YJ2DU, I_B000002VMD, I_B01I5AI96S, I_B00000136Z, I_B0884BK38T, I_B000063CNC, I_B0086449YA', 'history': {1: 'I_B000003A60'}}
3-sample {'candidates_positive': 'I_B00SSJIAXE, I_B07WP752DH', 'candidates_negative': 'I_B004EBT5CU, I_B00MA151ZQ, I_B008K9SG9K, I_B07WHMPTBH, I_B00GRHVIGU, I_B00DRIMVK4, I_B000065UFD, I_B00BQ1DAHC, I_B005N0C04Q, I_B002OFWG7E, I_B000JK8OYU, I_B0096MV73M, I_B07GRVBTTT, I_B013CWFOR6, I_B007I2BZIE, I_B08SZ425HV, I_B0039TD7PY, I_B00911LA76, I_B000066I4N, I_B00003002E, I_B000EXZI14, I_B072DX7DB7, I_B07PB2W4LF, I_B07G1YKQ57, I_B0002YJ2DU, I_B008B3MZNI, I_B002WIDRM6, I_B000KN7BRM, I_B000KN7BK4, I_B00000331T, I_B0161ZKIIQ, I_B000089RV6, I_B00AU15GLC, I_B00991TCOG, I_B00AYHKIZ6, I_B00XBWBWL0, I_B010T34MLU, I_B00NBNS94M, I_B009OXS8RQ, I_B0009ML256, I_B0036SPU3K, I_B013JB2LYO, I_B005HQ5S3G, I_B01JGW07FU, I_B00006JSS8, I_B01N8UJO9W, I_B00KE3BAM0, I_B000E6EJAW', 'history': {1: 'I_B01G3QL7XI', 2: 'I_B001JILQQ4', 3: 'I_B00ZW048DI'}}
5-sample {'candidates_positive': 'I_B005CAAYLS, I_B00VNQWTGI', 'candidates_negative': 'I_B00L326LTI, I_B00004RCW1, I_B00003002J, I_B0147Y0JSM, I_B000002LFZ, I_B00GKI40HU, I_B002YIHO7I, I_B0000032CU, I_B0050CJNJ2, I_B01M7RS0PW, I_B0012K1IMQ, I_B007ZU6H00, I_B01B6HIPWK, I_B000003G2K, I_B0079K2WR8, I_B00ZW048DI, I_B000002O2B, I_B0091V6SKK, I_B005H1SC8Y, I_B0096MV73M, I_B0007GAEVW, I_B001GQ2TGA, I_B00NQKWAIQ, I_B00M1SRBS8, I_B00UI23YDU, I_B08NMH3T3S, I_B000002A46, I_B01M1DKYSX, I_B06Y4DGVZC, I_B00MBVLDNE, I_B01NAF3ROL, I_B00R3TMCQG, I_B000AV2QLK, I_B074KLP1FL, I_B09BDLYPZF, I_B000002KBU, I_B000002JUC, I_B00991TCOG, I_B014RPCV82, I_B0000042MY, I_B00355ORGU, I_B00571VYGQ, I_B00FN3HRG4, I_B00000ICO0, I_B00C061HZY, I_B08MRW6MJT, I_B000000OQF, I_B0086449YA', 'history': {1: 'I_B000A7Q29G', 2: 'I_B00005KIZP', 3: 'I_B00560Q8KA', 4: 'I_B0037RBVDI', 5: 'I_B002A9MN7C'}}
10-sample {'candidates_positive': 'I_B000001E52, I_B000002MX7', 'candidates_negative': 'I_B006LQQ1GE, I_B000KN7BRM, I_B01CJ1SJQE, I_B00FR0GT9Y, I_B009NPA3Q4, I_B00008UAPM, I_B00EMAGCJM, I_B00631VJIC, I_B01I5AI96S, I_B00005Y1XY, I_B0001XPZGA, I_B0018Q7K2G, I_B06XSYRLXL, I_B00ERH15DI, I_B005RYF5H2, I_B009AWREEO, I_B07DRRCVQT, I_B00FKAA3MA, I_B00L5SFSN0, I_B00AU15HPC, I_B0754BBDF1, I_B01DDX9XA8, I_B00C7O8TSM, I_B000SO7OL6, I_B0884BK38T, I_B00NBXFAYY, I_B00CQGU9GG, I_B015HE05PI, I_B079PDLQV5, I_B009G7ZYPY, I_B00006879E, I_B00005BGV2, I_B07F99WH5Y, I_B000PFU7OO, I_B00AU15GLC, I_B00AYHKIZ6, I_B0000296J9, I_B005CA4F90, I_B07DXQ4SY4, I_B071HJ41VR, I_B0002YJ2DU, I_B00L4QYEGU, I_B0025KVLTW, I_B0000062FZ, I_B000002JUC, I_B003GAMPWM, I_B01JGW07FU, I_B001DUKHXQ', 'history': {1: 'I_B003V6L95K', 2: 'I_B001P4OACE', 3: 'I_B000002LQX', 4: 'I_B00470T06E', 5: 'I_B00008WI7H', 6: 'I_B000001DZ6', 7: 'I_B0000024JL', 8: 'I_B000002J9V', 9: 'I_B00000J2SB', 10: 'I_B000009NUE'}}

,title,category,description
I_1559617233,Brainwave Suite,"New Age, Meditation",We all experience many states of consciousness...
I_1568556888,Bobby Darin: Mack is Back,"Pop, Vocal Pop","Product Description, Now for the first time, v..."
I_1573300411,LIVE & LOUD,"International Music, Europe, British Isles, Br...",This is the first live home video in Ozzy's il...
I_1573306983,John Denver: The WILDlife Concert,"Pop, Singer-Songwriters","Celebrate John Denver's greatest hits with ""Th..."
I_1582703272,Body-Field Sound Healing,Today's Deals deprecated,The first-of-its-kind audio experience in whic...

history 8196

,title,category,description
I_0005164885,Christmas Eve and Other Stories,"Holiday & Wedding, Christmas","Product Description, A new sound for the seaso..."
I_0739003755,Music for Little Mozarts Sets for Lesson and D...,"Broadway & Vocalists, Musicals",Two compact disc recordings (sold as a two-dis...
I_1569383448,Bernadette Peters in Concert,"Pop, Vocal Pop","From the Back Cover, ""A diva who effuses sweet..."
I_1573306983,John Denver: The WILDlife Concert,"Pop, Singer-Songwriters","Celebrate John Denver's greatest hits with ""Th..."
I_6302320690,Neil Diamond: Love At The Greek VHS 1976,"Pop, Adult Contemporary",Love at the Greek [VHS]

candidates 4238
Movies_and_TV
1-sample {'candidates_positive': 'I_B00HW3EI3I, I_B094SRC3VY', 'candidates_negative': 'I_B00BCRRA8U, I_B00BUWD7Y8, I_B005OCFGTO, I_B00KHD5FK0, I_B004DK5CW4, I_B00X797NJW, I_B07NFBPT41, I_B00NCDVVLY, I_B006H5120E, I_B0000633U2, I_B000BPL2GK, I_B0087F7VSY, I_B00PGV9X5G, I_B0045HCJRG, I_B00KQTGWPC, I_B00HUFALRK, I_B00O4ZC57I, I_B00005JLHX, I_B01JAQEQOK, I_B005LJK3AC, I_B006O5Y1FK, I_B00AMSM9CW, I_B0713MM9DT, I_B00K2CHVJ4, I_B00SI7GDBM, I_B00E9ZAT4Y, I_B00APE1NZW, I_B004SEUJ82, I_B008JPZUYE, I_B00CNW9ZI6, I_B001NFNFMQ, I_B01MTD0LE5, I_B00AATV046, I_B00KKGS1KK, I_B00B1LN8WY, I_B017V2IG6O, I_0790731533, I_B000WC38BO, I_B00XQ13ZSO, I_B00WAJ8QCS, I_B01LTHXYXM, I_B009EEVSTK, I_B01JTQ3LFG, I_B00B4804KS, I_B002SAMMEC, I_B000BX5X5I, I_B00WG1DDFU, I_B00DYQ1G78', 'history': {1: 'I_B00OPNQ66K'}}
3-sample {'candidates_positive': 'I_B072JLDDMT, I_B00DPH7V8E', 'candidates_negative': 'I_B073ZQ3DZQ, I_B00EV4EUT8, I_B00UI5CU6Y, I_B00DKS3QZU, I_B07S86K91M, I_B01C6JFGFQ, I_B00NCDVVLY, I_B01B2CX0LU, I_B0045HCJHG, I_B00H9KKGTO, I_B00UTJ93FU, I_6305236569, I_B07N1XLCLN, I_B00DL48BM6, I_B0072OFM28, I_B0044IAB0S, I_B00005LOL0, I_B00HNER00Y, I_B00FAVRHBE, I_B013DS3COG, I_B017APV7HM, I_B019YHGHX8, I_B00HV8TN7K, I_B01J4STKWC, I_B00DTOYMGW, I_B002PMV9FG, I_B00PYLT0OW, I_B000A2WAQU, I_B07HGH7ZVM, I_B01H8AKTO6, I_B00SI7GCJK, I_B000NQRE1E, I_B007XF0WXA, I_B07GW2RHQD, I_B07886H8TF, I_B00V3QQF6I, I_B0068FZ0W4, I_B00H921DK8, I_B004SIP7ZS, I_B009TGXLZM, I_B0142G2NM0, I_B00AUDQFU6, I_B00LLHKCZ4, I_B00N8JIFPM, I_B00AHSH56C, I_B00ADS98FC, I_B07DQ3ZWYS, I_B07SV5HH14', 'history': {1: 'I_B01LTHMWRQ', 2: 'I_B071KGF7BW', 3: 'I_B07239FN76'}}
5-sample {'candidates_positive': 'I_B074JMXYPX, I_B073YB17T6', 'candidates_negative': 'I_B00HEPEBWC, I_B009DS6YGO, I_B00F9F1K8W, I_B00H83EV5W, I_B077H1ZBP3, I_B003LMPKSQ, I_B001DWNUII, I_B01N9YXQ5F, I_B00AUDQFU6, I_B01DAWJ9OC, I_B00E3QJ8DC, I_B00B4804KS, I_B00KX44P22, I_B00FEC4B54, I_B00M25DDQE, I_B00CDTSFF8, I_B0031XYLWG, I_B01LW32XQV, I_B003ASLJK4, I_B00K7IPGS6, I_B009UWYFFK, I_6317631093, I_B01H2JPTDO, I_B00005JKFA, I_B00M0JU1XU, I_B007RKFXQW, I_B014E1TJV6, I_B017MI0Z9I, I_B01MZIQ2WO, I_B00R2LZ41K, I_B00A7OIXW6, I_B01MAZGH7Z, I_B000SFOW8I, I_B06XGY67WQ, I_B006H5120E, I_B00AB65RUG, I_B0084IHVGG, I_B00JJ20QR2, I_B008Y7HKBI, I_B00ANGICCO, I_B00744WZ6W, I_B00ESGZ232, I_0790731533, I_B004SIP7ZS, I_B01MTD0LE5, I_B001NFNFMQ, I_B07894ZBDN, I_B00KB01Q4S', 'history': {1: 'I_B000VEMM3S', 2: 'I_B01E09H1VM', 3: 'I_B071923K26', 4: 'I_B00W8VATHI', 5: 'I_B01G4EIG1A'}}
10-sample {'candidates_positive': 'I_B001B3LIO2, I_B004I85CY4', 'candidates_negative': 'I_B00B1E6FF8, I_B005SFR7YE, I_B015HM3E8K, I_B013539XIS, I_B011KK9J7S, I_B00BSBU4EC, I_B000MRNWKG, I_B00LG6YEKE, I_B00JKJ0XJU, I_B008QZ5PY2, I_B006GHA9QQ, I_B000TGUUFA, I_B0000633U2, I_B01IARNQJ6, I_B001F76OKC, I_B01JCV3NF6, I_B00BLCHZC2, I_B01AB7II1E, I_B013FCLEIG, I_B00N1JQ3RQ, I_B000NQRE1E, I_B000BX5X5I, I_B00AJLHVES, I_B002C6A6N6, I_B008ETVXQY, I_B00AMR5FGA, I_B00KW274SM, I_B071S71D4N, I_B019QXXHB0, I_B0000714BP, I_B00C8CQRQ4, I_B01NBH6H8M, I_B005DVIPY4, I_B0032LV4NG, I_B0000DIXDR, I_B00BEL4QFO, I_B01I5SLS9A, I_B00ESY7QXI, I_B01GPLDCPW, I_B008JFUO4U, I_B07JGG5FNT, I_B002PQ7JQK, I_B017V2IG6O, I_B003L77GG0, I_B009CG9LZI, I_B00005JKTY, I_B0044IAB0S, I_0780623746', 'history': {1: 'I_B004M9ZHYE', 2: 'I_B007TBJD1U', 3: 'I_B0000DZTIT', 4: 'I_B008MILL9G', 5: 'I_B002O3Z4VG', 6: 'I_B000KEG938', 7: 'I_B00AEBB8PQ', 8: 'I_B008518MOW', 9: 'I_B000QTD368', 10: 'I_B0049GYXCC'}}

,title,category,description
I_0310427754,Doing the Right Thing: Making Moral Choices in...,"Genre for Featured Categories, Faith & Spiritu...","In this six-session, small group Bible study D..."
I_0323046371,Mosby's Nursing VideoSkills: Care of Infants a...,"Genre for Featured Categories, Special Interests",Mosby's Nursing Skills Video: Care of Infants ...
I_0739060287,The Master Drummer,"Featured Categories, DVD, Music Videos & Concerts","The Master Drummer, is based on over 40 years ..."
I_0767802624,Men in Black (Collector's Series),"Science Fiction & Fantasy, Science Fiction, Al...",Men in Black follows the exploits of Agents Ka...
I_0767806239,Seven Years in Tibet,"Studio Specials, Sony Pictures Home Entertainm...",Brad Pitt stars in the soaring adventure and i...

history 7798

,title,category,description
I_0739040375,"Paul Gilbert: Intense Rock, Vol. 1 and 2 [DVD]","Genre for Featured Categories, Music Videos & ...","Intense Rock: Complete, combines, Intense Rock..."
I_076780676X,Guarding Tess,"Studio Specials, Sony Pictures Home Entertainm...",What do you do with a former First Lady who's ...
I_0767812182,Thunderheart,"Studio Specials, Sony Pictures Home Entertainm...","Val Kilmer, Sam Shepard and Graham Greene star..."
I_0767817664,Fright Night,"Studio Specials, Sony Pictures Home Entertainm...","Meet Jerry Dandridge. He's sweet, sexy, and he..."
I_0767821556,"Bell, Book and Candle","Studio Specials, Sony Pictures Home Entertainm...","Meet Gillan Holroyd (Kim Novak), Greenwich Vil..."

candidates 4227
Toys_and_Games
1-sample {'candidates_positive': 'I_B00XLO0MB4, I_B08KSJX5J5', 'candidates_negative': 'I_B00428LJ0G, I_B0BGCRZPMS, I_B000KHZ044, I_B00V036C08, I_B0033RVDVC, I_B09CQMVL5Z, I_B019ICFYNI, I_B07W1VSQXK, I_B0C9RLNDXT, I_B000K8FYAS, I_B015OU8W3M, I_B07HD27YZT, I_B09PMNTFKG, I_B0792X1RSC, I_B0BSNN8G5G, I_B082YV8YB8, I_B001PME3FA, I_B000CBSNRY, I_B099F4N7X2, I_B0B1QQ3Q34, I_B00OZECKFK, I_B001RE8LMW, I_B095L997HN, I_B004S8F7QM, I_B0051BH6IM, I_B012CRQ7S2, I_B003OFKBHA, I_B0C6Y9HYJT, I_B0B3C48Q4S, I_B0C84YL64X, I_B000N5QNSK, I_B000F3V2MW, I_B07R7XGBQ5, I_B08CHLCGG5, I_B0BNLK925T, I_B08P1LJQ8D, I_B0B1VNSLX8, I_B07T3WDWHQ, I_B0C41HH3KK, I_B07T89WJ13, I_B00EFDXAB4, I_B0C82XC86B, I_B00U26V9CU, I_B0B4BQSBGC, I_B0C31MBVNK, I_B003621UT4, I_B01KYYKECA, I_B0B9S57TBM', 'history': {1: 'I_B07JVHFVQG'}}
3-sample {'candidates_positive': 'I_B00000IZKX, I_B00L2KCATG', 'candidates_negative': 'I_B09MH514FH, I_B00EFDXAB4, I_B003Y6E6IE, I_B0B418HJJN, I_B00U26V4VQ, I_B002YIRKKY, I_B07WDNCLKC, I_B0C32WFGYR, I_B0BZSZXJRF, I_B09RRDFXK2, I_B000URL296, I_B0BL3R86WG, I_B00S5FESNC, I_B003VYAJMG, I_B01IBSSBV2, I_B01MY72QQT, I_B0BNKGG19Q, I_B000G8S436, I_B00IHHLN5E, I_B08TD1Y1W7, I_B0BV8DDRPC, I_B00OT7NC5K, I_B0045O75AU, I_076245945X, I_B0BNR38641, I_B0BG32DSWS, I_B002L3TS5M, I_B0BPNH8W3R, I_B00419T56Q, I_B00U7EXD2G, I_B01LYNRB3Y, I_B09CQMVL5Z, I_B07D4T2XKB, I_B00QGSMK8K, I_B0000U11LW, I_B007PVHMCG, I_B000VSAEYI, I_B00004YO15, I_B073PW29V5, I_B0C72QDX3K, I_B00AHAJGXK, I_B0B4TQLDXT, I_B071WT3JKN, I_B07G1B9KDP, I_B0842M13NL, I_B00IZC6C8E, I_B0BQLY3H56, I_B07V3FM9ZV', 'history': {1: 'I_B088W5VSFZ', 2: 'I_B08ZRY2LS1', 3: 'I_B08JLP3PFG'}}
5-sample {'candidates_positive': 'I_B087H2M9FW, I_B01NAGLBAL', 'candidates_negative': 'I_B00104MFRG, I_B07XRFGMMV, I_B082YVP52W, I_B08N6GPR6G, I_B0B4TS3LNY, I_B08NBDGTBF, I_B01NBXZGVP, I_B003Y6E6IE, I_B007YCMCIA, I_B0C41HH3KK, I_B0BRSD3YP1, I_B07C3N1FWY, I_B07Y7BRB8R, I_B0C32QMKKT, I_B000MRGWRQ, I_B08KXGHX9V, I_B09F9LZSWY, I_B00K1LGNWW, I_B075QRWRYP, I_B0B8GP7MNG, I_B07NRT2CYD, I_B000284ZNI, I_B0C31MBVNK, I_B084K4J1C4, I_B09X13LW26, I_B07BC6SG83, I_B0BZGHYHC9, I_B00A2HD40E, I_B08248TYB5, I_B0B418HJJN, I_B085RH2V95, I_B09NMGC4HC, I_B00IHHLN5E, I_B004U7JJWE, I_B002YIRKKY, I_B074XNXTC6, I_B000GJIU3E, I_B0BKR9BZFV, I_B071YQQFXN, I_B07WRM9X7J, I_B000IFZ6LA, I_B09MVL1P2R, I_B0BRKVYF32, I_B07ZHWN2MZ, I_B000062SPJ, I_B00KXZC762, I_B0BFKSPRR4, I_B09G4MP3XD', 'history': {1: 'I_B000P6Q7MY', 2: 'I_B007YDCOLY', 3: 'I_B008QFS120', 4: 'I_B00C0QS2PM', 5: 'I_B00J4S57O8'}}
10-sample {'candidates_positive': 'I_B01JCR23FG, I_B01JCR214E', 'candidates_negative': 'I_B07T89WJ13, I_B0BFD449WN, I_B0000789T2, I_B01LALE67U, I_B09PH8Z5R8, I_B001PME3FA, I_B07BXMDF7G, I_B07R7W3LM4, I_B0843H25SK, I_B000VSAF2O, I_B0BG94QRLZ, I_B0C8WGG2SP, I_B0BKR9BZFV, I_B00IHHLN5E, I_B09PBM7RJD, I_B003AVIO4K, I_B0B4DRWZ51, I_B09S19HRY9, I_B00EFDXAB4, I_B09RRDFXK2, I_B08PP7NKFP, I_B082YV8YB8, I_B0C31MBVNK, I_B0CB97ZFH4, I_B000CBSNRY, I_B07D8K8J8X, I_B0C7LNHF2R, I_B0B4TS3LNY, I_B07GWZNF91, I_B00DSIQS6G, I_B09XF7CSBZ, I_B009Z7E8GG, I_B01M5KEOI6, I_B0842LFJHK, I_B08DYGDQLP, I_B0BCWT5JX8, I_B09GQ8T6N4, I_B094HV4TZ5, I_B0BJKM5ST5, I_B0BW36JSPP, I_B0B4TR2ZV5, I_B0C5FDCX69, I_B0B6GF2GTJ, I_B00000IV34, I_B0C3GL76CN, I_B0BVV4XKJ1, I_B09X2381JH, I_B00Y53XH9O', 'history': {1: 'I_B07DQ6BWPV', 2: 'I_B07K7JTZYB', 3: 'I_B0BKQ19QFF', 4: 'I_B07FW41MVD', 5: 'I_B071JZ6L7W', 6: 'I_B004PBO97K', 7: 'I_B0781GK1H8', 8: 'I_B07G77GLXJ', 9: 'I_B075X26FHP', 10: 'I_B0002HR7Y8'}}

,title,category,description
I_0020232233,"Dungeons & Dragons - ""Storm Kings Thunder"" DM ...","Games & Accessories, Game Accessories, Game Pi...",This screen has been specifically built with t...
I_0545346231,Klutz Twisted Critters: The Pipe Cleaner Book,NaN,Twisted Critters is our new and updated take o...
I_0764958070,Charley Harper Monteverde 1000 Piece Jigsaw Pu...,NaN,"Product Description, null, About the Author, C..."
I_078696555X,Wizards of the Coast A78490000 Dungeon! Fantas...,"Games & Accessories, Board Games",A family classic- updated for the next generat...
I_0976914476,Slugfest Games The Red Dragon Inn 3 Strategy B...,"Games & Accessories, Board Games",Once again you and your adventuring companions...

history 8180

,title,category,description
I_0545498562,"Make Clay Charms (Klutz Craft Kit) 8"" Length x...","Arts & Crafts, Craft Kits, Jewelry","Product Description, Make Clay Charms features..."
I_0545906520,"Klutz Sew Mini Treats Craft Kit, 8"" Length x 1...","Arts & Crafts, Craft Kits",Stitch and stuff your favorite plush foods wit...
I_0735339384,Mudpuppy Illustrated Spanish to English Flash ...,"Learning & Education, Flash Cards","Product Description, El gato = Cat. House = Ca..."
I_076245945X,Harry Potter: Collectible Quidditch Set - Acce...,"Novelty & Gag Toys, Gag Toys & Practical Jokes",Collect your own one-of-a-kind keepsake replic...
I_0764958070,Charley Harper Monteverde 1000 Piece Jigsaw Pu...,NaN,"Product Description, null, About the Author, C..."

candidates 4276
Sports_and_Outdoors
1-sample {'candidates_positive': 'I_B00MPE8GFK, I_B0744GWMMQ', 'candidates_negative': 'I_B0BS54CFF5, I_B017UMB0OA, I_B077X1SQY9, I_B00404R4NI, I_B00D3WV3VC, I_B07C2V3J7C, I_B00NPZ73QQ, I_B075HN78M9, I_B0BXHLWCR5, I_B07KG4179P, I_B01A04FLWW, I_B0C4MNRN7R, I_B004XADAQO, I_B09Q59D5SC, I_B07NYZS5VG, I_B07NVF3Q1R, I_B0C45XP1MM, I_B003V57NUQ, I_B0BCL6KCF8, I_B09TGBGM8D, I_B00701H384, I_B09JC1ZC2Y, I_B0B4JNZ875, I_B005AG4O42, I_B09GXBKQKN, I_B013FIVU0C, I_B08WQV6YPR, I_B07XBTG8QS, I_B0088ZVLAM, I_B0C48Q7YDS, I_B08225SJL5, I_B01LXGBP22, I_B07GBFYHNM, I_B001C1UGVO, I_B002VQ9PU2, I_B0BF1KKXMJ, I_B00P7MYS6I, I_B00GN85A3A, I_B09M4DCXH6, I_B00GN856F2, I_B07NWQSV2Y, I_B07R6NX9YF, I_B07ZSDK651, I_B0B5GP8JPB, I_B006JH1HDW, I_B001ASJDWW, I_B00873J0YY, I_B0BYDCRCW2', 'history': {1: 'I_B07BVBX3V2'}}
3-sample {'candidates_positive': 'I_B07G7TR8T4, I_B074PCX7N7', 'candidates_negative': 'I_B07DYB9G79, I_B07F95GK37, I_B07D6M2152, I_B0C78RCGWB, I_B00F9F6OVK, I_B000E3D2VM, I_B01F8KL3T8, I_B00339911O, I_B0C9R1YXX8, I_B07WVVV8H5, I_B00A8APWIW, I_B0B4JNZ875, I_B0BJXB8JBQ, I_B0C4MNRN7R, I_B09MJKJYLQ, I_B00M0ETE8S, I_B087LN31GG, I_B0BL9LRKDS, I_B00ULRCA0U, I_B0BX51XY2D, I_B0BZDBL46Z, I_B0C6TFV7KL, I_B01N2JHFY8, I_B002PLU912, I_B07M7XRQ7F, I_B08F9TBZPC, I_B001WJ577O, I_B000E35Y1S, I_B07V4TT551, I_B0BV3NKWB1, I_B09HCJZZCJ, I_B07CMK1G2B, I_B00KN7AIWK, I_B0BXZCSJHH, I_B0BSGY2V7P, I_B00NOLTQ2U, I_B008BSP7S8, I_B07H8WF5TF, I_B005543YUE, I_B00HUFVTIK, I_B08WNV9WSJ, I_B085W26BT8, I_B00G44X9D6, I_B004XADAQO, I_B0BG293TDW, I_B0BX2WK4V4, I_B07B8JWTZB, I_B0C7QFH7VC', 'history': {1: 'I_B00R6405SA', 2: 'I_B00GJJUTE8', 3: 'I_B001E3LNR6'}}
5-sample {'candidates_positive': 'I_B00LXTOPNU, I_B08K63CBQC', 'candidates_negative': 'I_B09VPB34YM, I_B0B784DJHN, I_B082GR49ZH, I_B09BLFYQNV, I_B0BPHXFZVF, I_B004NBNBNU, I_B07J5R75Y7, I_B07C3VB7WZ, I_B007Q4NCZI, I_B07C2WY224, I_B0C4D1CHTM, I_B075XZSL8T, I_B000VSKAI8, I_B01C7F40CE, I_B006QR1K46, I_B0B9X2DQB2, I_B0914WNBNM, I_B00ULRCA0U, I_B07MV6C2VN, I_B007CP6UK0, I_B00JYCPRSA, I_B001ZFIA6U, I_B097FXSJFV, I_B0BX2WK4V4, I_B07NYZS5VG, I_B077LH4S89, I_B0C1D5V5Y7, I_B093YQLCGL, I_B0C3R7W1CZ, I_B00QIM5CMK, I_B006JMK7N8, I_B09GY18FM5, I_B07TVF91X6, I_B07JPZ4C66, I_B08F9JDRCD, I_B01FHDZGGM, I_B000IXRDWW, I_B0BV8MT9BW, I_B07C9DHLTF, I_B0B8SWT79R, I_B002XMD2VM, I_B00C8RK66Q, I_B08QV2BCXR, I_B001V7B2OY, I_B0C5HSZ7RB, I_B0C7QFH7VC, I_B0055NRJLA, I_B0C36QT278', 'history': {1: 'I_B00RZV091W', 2: 'I_B00W0L837Y', 3: 'I_B019IFLZLA', 4: 'I_B008Z9J68K', 5: 'I_B006EPOP9M'}}
10-sample {'candidates_positive': 'I_B00KDKU7TG, I_B001CK0FK2', 'candidates_negative': 'I_B08VHJ8F5Z, I_B00PGBN11S, I_B07QXSLBW1, I_B003XPISEO, I_B00664KXGA, I_B01HL0B5AU, I_B006JMK7N8, I_B0CBTB6F7D, I_B01NBXOOJW, I_B0BL9TRHRF, I_B0C2DFTH8V, I_B001VS1M20, I_B00U2T894I, I_B013FIVU0C, I_B00172A3DE, I_B07P79GFYX, I_B003IX11YA, I_B003VRWZ3Y, I_B09JY9N8CX, I_B0C3LR1RCS, I_B07QTLFBKF, I_B0914WNBNM, I_B09WXV9H7X, I_B000IXRDWW, I_B0C3RDZ96K, I_B0033H7VI6, I_B096K6RT9T, I_B07DB3BC3Z, I_B000H6GZI8, I_B09VMB3ZXF, I_B00HMN7LDC, I_B01D4W8EEO, I_B078S454HZ, I_B0088ZVLAM, I_B0B6NZVWVX, I_B083RQFWZG, I_B0047ZADSI, I_B00RXGGZ3K, I_B00O80WA38, I_B0BQCDX46R, I_B09R9X84HF, I_B001MK3GFS, I_B00ADVKRRM, I_B001C1UGVO, I_B0C6B4BJTX, I_B074ZVWPLY, I_B0BXHLWCR5, I_B000EYULIS', 'history': {1: 'I_B0B66W3WVZ', 2: 'I_B008R5L4VY', 3: 'I_B00O66VK5I', 4: 'I_B0BX2WK4V4', 5: 'I_B000BT4F9C', 6: 'I_B07CBJNVB4', 7: 'I_B000H6J742', 8: 'I_B095X8G8GL', 9: 'I_B08BPBSM5K', 10: 'I_B000EBVR8Y'}}

,title,category,description
I_1609968417,Carson Dellosa Colorful Owls Shape Stickers (1...,"Fan Shop, Toys & Game Room",These colorful owl die-cut shape stickers are ...
I_1944788921,GymPad Mini Workout Journal - The Small Stylis...,"Exercise & Fitness, Accessories, Fitness Planners","Available in 4 different colours, which one wi..."
I_2094869245,5 LED Bicycle Rear Tail Red Bike Torch Laser B...,"Sports, Cycling, Accessories, Lights & Reflect...",This newly-designed Laser tail light can emit ...
I_7245456313,Black Mountain Products Resistance Band Set wi...,"Exercise & Fitness, Strength Training Equipmen...",Black Mountain Products (B.M.P.) resistance ba...
I_7500670133,Titanium Tornado Baseball Necklace Orange Blac...,"Sports, Team Sports, Baseball, Accessories",Materials emit energy that is effective in con...

history 8108

,title,category,description
I_1469393182,"Chicago Bears 2023 12"" x 12"" Team Wall Calendar","Fan Shop, Office Products, Calendars & Planners",Start the season off right with this team 2023...
I_7245456313,Black Mountain Products Resistance Band Set wi...,"Exercise & Fitness, Strength Training Equipmen...",Black Mountain Products (B.M.P.) resistance ba...
I_B0000ANBEZ,Coleman 3000000455 Latern Pump Kit,"Outdoor Recreation, Camping & Hiking, Camp Kit...",Coleman Liquid Fuel Lantern and Camp Stove Pum...
I_B0000AQQX3,"Fulton XP10 0101 Swivel Trailer Tongue Jack, 1...","Sports, Boating & Sailing, Boating, Boat Trail...",Fulton XP10 0101 Trailer Jack is designed for ...
I_B0000AUT1J,Coleman 3000000454 Filler Cap Lantern,"Outdoor Recreation, Camping & Hiking, Lights &...",Coleman 3000000454 filler cap. Camping lights ...

candidates 4326